name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"features":[{"create":{"domain":"appsalon-mvc-php-dwfs.sao.dom.my.id","user":"appsalon-mvc-php-dwfs","pass":"<redacted>","email":"gaboangel.co@gmail.com"}},"firewall","php
            8.3","mysql","ssl","ssl always","ssl","ssl
            always"],"source":"https://github.com/gabrielangel283/AppSalon-MVC-PHP-DWFS.git","root":"public_html/public","nginx":{"fastcgi":"on","locations":[{"match":"/","try_files":"$uri
            $uri/ /index.php$is_args$args"},{"match":"~
            \\.[^\\/]+(?<!\\.php)$","try_files":"$uri =404"}]},"commands":["echo
            \"<?php phpinfo(15);\" > phpinfo.php","echo \"display_errors = On\"
            > .user.ini","echo \"display_startup_errors = On\" >>
            .user.ini","echo \"DB_HOST=localhost\" > includes/.env","echo
            \"DB_USER=${USERNAME}\" >> includes/.env","echo
            \"DB_PASS=${PASSWORD}\" >> includes/.env","echo
            \"DB_NAME=${DATABASE}\" >> includes/.env","echo \"\" >>
            includes/.env","echo \"EMAIL_HOST=sandbox.smtp.mailtrap.io\" >>
            includes/.env","echo \"EMAIL_USER=${{ secrets.EMAIL_USER }}\" >>
            includes/.env","echo \"EMAIL_PASS=${{ secrets.EMAIL_PASS }}\" >>
            includes/.env","echo \"EMAIL_PORT=587\" >> includes/.env","echo \"\"
            >> includes/.env","echo \"PROJECT_URL=https://${DOMAIN}\" >>
            includes/.env","composer install"]}